src/AppBundle/Entity/DocumentDescription.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * DocumentDescription
 *
 * @ORM\Table(name="document_description")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\DocumentDescriptionRepository")
 */
class DocumentDescription
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="document_id", type="integer", nullable=true, length=11)
     */
    private $document_id;

    /**
     * @var int
     *
     * @ORM\Column(name="language_id", type="integer", length=11)
     */
    private $language_id = 1;

    /**
     * @var string,
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string,
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var string,
     *
     * @ORM\Column(name="short_description", type="text")
     */
    private $short_description;

    /**
     * @var string,
     *
     * @ORM\Column(name="meta_description", type="text")
     */
    private $meta_description;

    /**
     * @var string
     *
     * @ORM\Column(name="meta_h1", type="string", length=255)
     */
    private $meta_h1;

    /**
     * @var string
     *
     * @ORM\Column(name="meta_keyword", type="string", length=255)
     */
    private $meta_keyword;

    /**
     * @var string
     *
     * @ORM\Column(name="meta_title", type="string", length=255)
     */
    private $meta_title;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set documentId
     *
     * @param integer $documentId
     *
     * @return DocumentDescription
     */
    public function setDocumentId($documentId)
    {
        $this->document_id = $documentId;

        return $this;
    }

    /**
     * Get documentId
     *
     * @return int
     */
    public function getDocumentId()
    {
        return $this->document_id;
    }

    /**
     * Set languageId
     *
     * @param integer $languageId
     *
     * @return DocumentDescription
     */
    public function setLanguageId($languageId)
    {
        $this->language_id = $languageId;

        return $this;
    }

    /**
     * Get languageId
     *
     * @return int
     */
    public function getLanguageId()
    {
        return $this->language_id;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return DocumentDescription
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set short_description
     *
     * @param string $short_description
     *
     * @return DocumentDescription
     */
    public function setShortDescription($short_description)
    {
        $this->short_description = $short_description;

        return $this;
    }

    /**
     * Get short_description
     *
     * @return string
     */
    public function getShortDescription()
    {
        return $this->short_description;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return DocumentDescription
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set metaDescription
     *
     * @param string $metaDescription
     *
     * @return DocumentDescription
     */
    public function setMetaDescription($metaDescription)
    {
        $this->meta_description = $metaDescription;

        return $this;
    }

    /**
     * Get metaDescription
     *
     * @return string
     */
    public function getMetaDescription()
    {
        return $this->meta_description;
    }

    /**
     * Set metaH1
     *
     * @param string $metaH1
     *
     * @return DocumentDescription
     */
    public function setMetaH1($metaH1)
    {
        $this->meta_h1 = $metaH1;

        return $this;
    }

    /**
     * Get metaH1
     *
     * @return string
     */
    public function getMetaH1()
    {
        return $this->meta_h1;
    }

    /**
     * Set metaKeyword
     *
     * @param string $metaKeyword
     *
     * @return DocumentDescription
     */
    public function setMetaKeyword($metaKeyword)
    {
        $this->meta_keyword = $metaKeyword;

        return $this;
    }

    /**
     * Get metaKeyword
     *
     * @return string
     */
    public function getMetaKeyword()
    {
        return $this->meta_keyword;
    }

    /**
     * Set metaTitle
     *
     * @param string $metaTitle
     *
     * @return DocumentDescription
     */
    public function setMetaTitle($metaTitle)
    {
        $this->meta_title = $metaTitle;

        return $this;
    }

    /**
     * Get metaTitle
     *
     * @return string
     */
    public function getMetaTitle()
    {
        return $this->meta_title;
    }

    /**
     * @ORM\OneToOne(targetEntity="Document", inversedBy="description")
     * @ORM\JoinColumn(name="document_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $document;

    public function setDocument(Document $document)
    {
        $this->document = $document;
    }

    public function getDocument()
    {
        return $this->document;
    }
    
    public function __clone() 
    {
        $this->id           = NULL;
        $this->document_id  = NULL;
        $this->document     = NULL;
    }
}

src/AppBundle/Entity/Field.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use AppBundle\Entity\FieldDescription;
use AppBundle\Entity\Code;

/**
 * Field
 *
 * @ORM\Table(name="field")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\FieldRepository")
 */
class Field
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="document_id", nullable=true, type="integer", length=11)
     */
    private $document_id;

    /**
     * @var int
     *
     * @ORM\Column(name="parent_id", type="integer", nullable=true, length=11)
     */

    private $parent_id;

    /**
     * @var int
     *
     * @ORM\Column(name="group_id", type="integer", nullable=true, length=11)
     */
    private $group_id;
    
    /**
     * @var int
     *
     * @ORM\Column(name="code_id", type="integer", nullable=true, length=11)
     */
    private $code_id;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status = 1;

    /**
     * @var bool
     *
     * @ORM\Column(name="choice", type="boolean")
     */
    private $choice = false;

    /**
     * bool
     *
     * name="delete", type="boolean"
     */
    private $delete = false;
    
    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;
    
    /**
     * @var string
     *
     * @ORM\Column(name="value", type="text")
     */
    private $value = '';

    /**
     * @var int
     *
     * @ORM\Column(name="sort", type="integer", length=11)
     */

    private $sort = 0;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_up", type="datetime")
     */
    private $date_up;

    /**
     * Many Fields have One Documents.
     * @ORM\ManyToOne(targetEntity="Document", inversedBy="fields")
     * @ORM\JoinColumn(name="document_id", referencedColumnName="id")
     */
    private $document;

    /**
     * One Field has One Field.
     * @ORM\OneToOne(targetEntity="Field", mappedBy="parent")
     */
    private $child;

    /**
     * One Field have One Field.
     * @ORM\OneToOne(targetEntity="Field", inversedBy="child", cascade={"All"})
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * One Field has Many Fields.
     * @ORM\OneToMany(targetEntity="Field", mappedBy="group", cascade={"All"})
     */
    private $elements;

    /**
     * Many Fields have One Field.
     * @ORM\ManyToOne(targetEntity="Field", inversedBy="elements", cascade={"All"})
     * @ORM\JoinColumn(name="group_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $group;
    
    /**
     * Many Fields have One Code.
     * @ORM\ManyToOne(targetEntity="Code", inversedBy="fields", cascade={"persist"})
     * @ORM\JoinColumn(name="code_id", referencedColumnName="id")
     */
    private $code;
    
    /**
     * @ORM\OneToOne(targetEntity="FieldDescription", mappedBy="field", cascade={"All"})
     */
    private $description;

    /*GETTERS METHODS*/

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Get group_id
     *
     * @return int
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * Get document
     *
     * @return Document
     */
    public function getDocument() {
        return $this->document;
    }

    /**
     * Get parent
     *
     * @return Field
     */
    public function getParent()
    {
        return $this->parent;
    }
    
    /**
     * Get parent_id
     *
     * @return Field
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Get group
     *
     * @return Field
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Get choice
     *
     * @return \int
     */
    public function getChoice()
    {
        return $this->choice;
    }

    /**
     * Get delete
     *
     * @return \bool
     */
    public function getDelete()
    {
        return $this->delete;
    }

    /**
     * Get code
     *
     * @return \string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }
    
    /**
     * Get type
     *
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Get sort
     *
     * @return \int
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * Get dateUp
     *
     * @return \DateTime
     */
    public function getDateUp()
    {
        return $this->date_up;
    }

    /**
     * Get description
     *
     * @return FieldDescription
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * Get child
     *
     * @return Field
     */
    public function getChild()
    {
        return $this->child;
    }

    /**
     * Get elements
     *
     * @return ArrayCollection
     */
    public function getElements()
    {
        return $this->elements;
    }
    /*END GETTERS METHODS*/

    /*SETTER METHODS*/

    /**
     * Set document
     *
     * @return Field
     */
    public function setDocument(Document $document) {
        $this->document = $document;

        return $this;
    }

    /**
     * Set parent
     *
     * @return Field
     */
    public function setParent($field)
    {
        $this->parent = $field;

        return $this;
    }

    /**
     * Set group
     *
     * @return Field
     */
    public function setGroup($field)
    {
        $this->group = $field;

        return $this;
    }

    /**
     * Set status
     *
     * @param integer $status
     *
     * @return Field
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Set choice
     *
     * @param \int $choice
     *
     * @return Field
     */
    public function setChoice($choice)
    {
        $this->choice = $choice;

        return $this;
    }

    /**
     * Set delete
     *
     * @param \int $delete
     *
     * @return Field
     */
    public function setDelete($delete)
    {
        $this->delete = $delete;

        return $this;
    }

    /**
     * Set code
     *
     * @param \string $code
     * @return Field
     */
    public function setCode(Code $code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Set type
     *
     * @param string $type
     *
     * @return Field
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }
    
    /**
     * Set value
     *
     * @param string $value
     *
     * @return Field
     */
    public function setValue($value)
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Set sort
     *
     * @param \int $sort
     *
     * @return Field
     */
    public function setSort($sort)
    {
        $this->sort = $sort;

        return $this;
    }

    /**
     * Set dateUp
     *
     * @param \DateTime $dateUp
     *
     * @return Field
     */
    public function setDateUp($dateUp)
    {
        $this->date_up = $dateUp;
        return $this;
    }
    
    /**
     * Set description
     *
     * @return Field
     */
    public function setDescription(FieldDescription $description) {
        $this->description = $description;
        return $this;
    }
    
    /**
     * Add Elem
     *      
     * @return Field
     */
    public function addElem(Field $Field)
    {
        $this->elements[] = $Field;
        return $this;
    }
    
    /**
     * Add Child
     *      
     * @return Field
     */
    public function setChild(Field $Field)
    {
        $this->child = $Field;
        return $this;
    }

    /*END SETTER METHODS*/

    /*CONSTRUCT METHOD*/
    function __construct()
    {
        $this->date_up          = new \DateTime("now");
        $this->description      = new FieldDescription();
        $this->code             = new Code();
        $this->elements         = new ArrayCollection();
    }

    public function __toString()
    {
        if($this->getDescription()->getName()){
            return $this->getDescription()->getName();
        }
        return 'Field';
    }
    

}

src/AppBundle/Controller/DocumentController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Document;

class DocumentController extends Controller
{
        
     /**
     * @Route("/document/add", name="document_add")
     */
    public function addAction(Request $request)
    {
            
        if($request->get('document_id') != NULL && $request->get('fields') != NULL)
        {
            $data['fields']         = $request->get('fields');
            $data['document_id']    = (int)$request->get('document_id');
            $data['user']           = $this->getUser();
            
            $Repository = $this->getDoctrine()->getRepository(Document::class);
                        
            $Document = $Repository->addDocumentUser($data);
            
            $content = $Repository->getContent($Document);
            
            $fileName = $Document->getSlug() . '_'  . md5(time()) . '_' . $Document->getId() . '.pdf';
            
            $this->get('knp_snappy.pdf')->generateFromHtml(
                $this->renderView('AppBundle:PDF:index.html.twig', ['content' => $content]), './app/pdf/' .$fileName                
            );
            
            $Document->setLink($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($Document);
            $em->flush();
        }
        return $this->redirectToRoute('personal');
    }

    /**
     * @Route("/document/{slug}", name="document_show" , requirements={"slug": "^[0-9a-zA-Z\-]{4,200}$"})
     */
    public function showAction($slug)
    {
        $Document = $this->getDoctrine()
            ->getRepository(Document::class)
            ->getDocument($slug);
        //dump($slug); die();
        return $this->render('AppBundle:Document:index.html.twig', ['Document' => $Document]);
    }
    
   
}

src/AppBundle/Resources/views/Document/index.html.twig
{{ render(controller('AppBundle:Header:Index', { 'Meta':Document })) }}
<div id="document">
    <!-- OPEN CONTENT  -->    
    <section class="document">
        <div class="container">  
            <div class="row">
                <div class="col-md-9">
                    <header class="doc-header">{{ Document.description.name }} <span class="price"> {{ Document.price }}  грн.</span></header>                   
                    <div class="panel-grey">
                        {{ Document.description.shortDescription|raw }}
                    </div>
                    {% if is_granted('ROLE_USER') or is_granted('ROLE_ADMIN') %}
                    <form action="{{ path('document_add') }}" method="post">                
                        <header class="doc-header">Информация для формирования документа</header>
                        <div class="row">
                            <input name="document_id" type="hidden" value="{{Document.id}}"/>
                            {% for field in Document.fields %}
                                {% if field.type == 'text' %}
                                    <div class="col-sm-6">
                                        <label>{{field.description.name}}</label>
                                        <input name="fields[{{field.id}}]" value="" type="text"/>
                                    </div>
                                {% endif %}
                                {% if field.type == 'number' %}
                                    <div class="col-sm-6">
                                        <label>{{field.description.name}}</label>
                                        <input name="fields[{{field.id}}]" value="" type="number"/>
                                    </div>
                                {% endif %}
                                {% if field.type == 'date' %}
                                    <div class="col-sm-6">
                                        <label>{{field.description.name}}</label>
                                        <input name="fields[{{field.id}}]" type="date"/>
                                    </div>
                                {% endif %}
                                {% if field.type == 'checkbox' %}
                                    <div class="col-sm-6">
                                        <label for="field-{{field.id}}">{{field.description.name}}</label>
                                        <input id="field-{{field.id}}" name="fields[{{field.id}}]" type="checkbox" {% if field.choice %} checked  {% endif %} />
                                    </div>
                                {% endif %}
                                {% if field.type == 'radio_list' %}
                                    <div class="col-sm-12">
                                        <div class="list-header">{{field.description.name}}</div>
                                    </div>
                                {% endif %}    
                                {% if field.type == 'radio_el' %}
                                     <div class="col-sm-6">
                                         <input id="field-{{field.id}}" name="fields[{{field.groupId}}]" type="radio" {% if field.choice %} checked  {% endif %} value="{{field.id}}" />
                                         <label for="field-{{field.id}}"> {{field.description.name}}</label>
                                    </div>
                                {% endif %} 
                                {% if field.type == 'del' %}
                                    <div class="col-md-12 field-del">
                                        {% if field.description.description %}
                                            <div class="alert green">{{field.description.description}}</div>
                                        {% else %}
                                            <hr>
                                        {% endif %}
                                    </div>
                                {% endif %} 
                            {% endfor %}
                        </div>
                        <button class="next" style="color: #fff" type="submit">Добавить</button>
                    </form>
                    {% else %}
                    Для использования конструктора документа необходимо <a href="{{path('login')}}">войти</a> или <a href="{{path('registration')}}">зарегистрироваться</a>
                        
                    {% endif %}
                </div>
                <div class="col-md-3">
                    <aside>
                        <a class="back" href="{{ path('category_show', {'slug': 'konstruktor-yuridicheskih-dokumentov'}) }}">
                            <img src="{{ asset('app/img/icon-arrow-left.png') }}"/>
                            Назат к списку документов
                        </a>
                        <header class="doc-header">Похожие документы:</header>
                        <a class="btn-light" href="#">Доверинность для банковского счета</a>
                        <a class="btn-light" href="#">Доверинность для банковского счета</a>
                    </aside>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- END CONTENT  -->
</div>

{{ render(controller('AppBundle:Footer:Index')) }}

src/AppBundle/Resources/views/Document/load.html.twig
{{ render(controller('AppBundle:Header:Index', { 'Meta':Document })) }}
<div id="load">
    <!-- OPEN CONTENT  -->    
    <section class="document">
        <div class="container">  
            <div class="row">
                <div class="col-md-12">
                    <a target="__blank" href="{{ asset(link) }}" >Скачать {{Document.description.name}} в PDF</a>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- END CONTENT  -->
</div>

{{ render(controller('AppBundle:Footer:Index')) }}